"""Generate browser DTOs and validation constants from Python's authoritative definitions."""

import argparse
import hashlib
import json
import sys
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from pydantic.alias_generators import to_camel  # noqa: E402

from app.domain.enums import FlowVersion  # noqa: E402
from app.domain.flow import FIELD_FOR_STEP, FLOW_STEPS, STEPS  # noqa: E402
from app.domain.rules import CM_PER_METRE, INPUT_RULES, JEV_RULES  # noqa: E402
from app.schemas.payment import PaymentView
from app.schemas.result import FreeResult, MemberResult  # noqa: E402
from app.schemas.session import SessionView  # noqa: E402


def typescript(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(typescript(item) for item in schema["anyOf"])
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "object":
        # These are serialization DTOs: FastAPI includes default and null fields.
        return (
            "{\n"
            + "\n".join(
                f"  {name}: {typescript(value)};"
                for name, value in schema.get("properties", {}).items()
            )
            + "\n}"
        )
    if kind == "array":
        return f"({typescript(schema['items'])})[]"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }[kind]


def generate():
    schemas = {}
    for model in (SessionView, FreeResult, MemberResult, PaymentView):
        schema = model.model_json_schema(mode="serialization", by_alias=True)
        schemas.update(schema.pop("$defs", {}))
        schemas[model.__name__] = schema
    content = "// Generated by scripts/generate_frontend_contract.py; do not edit.\n"
    content += "\n".join(
        f"export type {name} = {typescript(schema)};" for name, schema in sorted(schemas.items())
    )
    constants = {
        "inputRules": {to_camel(k): v for k, v in asdict(INPUT_RULES).items()},
        "steps": list(STEPS),
        "guidedFlowVersion": FlowVersion.guided,
        "lifestyleFlowVersion": FlowVersion.lifestyle,
        "flowSteps": {version: list(steps) for version, steps in FLOW_STEPS.items()},
        "fields": {step: to_camel(field) for step, field in FIELD_FOR_STEP.items()},
        "cmPerMetre": CM_PER_METRE,
        "gradualEffortThreshold": JEV_RULES.gradual_effort_threshold,
    }
    content += (
        "\n"
        + "\n".join(
            f"export const {name} = {json.dumps(value)} as const;"
            for name, value in constants.items()
        )
        + "\n"
    )
    from plan_translation_fixture import fixture_messages

    from app.main import app

    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output-dir", default="contracts")
    args = parser.parse_args()
    files = {
        "contract.ts": content,
        "openapi.json": json.dumps(app.openapi(), ensure_ascii=False, indent=2) + "\n",
        "plan-fixtures.json": json.dumps(fixture_messages(), ensure_ascii=False, indent=2) + "\n",
    }
    manifest = {
        "version": "0.2.0",
        "sha256": {name: hashlib.sha256(body.encode()).hexdigest() for name, body in files.items()},
    }
    files["manifest.json"] = json.dumps(manifest, indent=2) + "\n"
    target = Path(args.output_dir)
    for name, body in files.items():
        file = target / name
        if args.check:
            if not file.exists() or file.read_text(encoding="utf-8") != body:
                raise SystemExit(f"Stale contract artifact: {name}")
        else:
            target.mkdir(parents=True, exist_ok=True)
            file.write_text(body, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    generate()
